spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_demo  # PostgreSQL URL ve veritabanı adınız
    username: postgres  # PostgreSQL kullanıcı adınız
    password: 12345  # PostgreSQL şifreniz
    driverClassName: org.postgresql.Driver  # PostgreSQL JDBC sürücüsü
  jpa:
    hibernate:
      ddl-auto: update  # 'create-drop' her uygulama yeniden başlatıldığında veritabanını sıfırlar, 'update' sadece değişiklikleri uygular
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQL diyalekti

security:
  jwt:
    secret: "burakburakburakburakburakburakburakburakburakburakburakburakbura"